-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 03:18:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ewaiter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ewaiter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ewaiter` DEFAULT CHARACTER SET utf8 ;
USE `ewaiter` ;

-- -----------------------------------------------------
-- Table `ewaiter`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ewaiter`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ewaiter`.`caffe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ewaiter`.`caffe` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `account_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `caffe_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `ewaiter`.`account` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `account_id` ON `ewaiter`.`caffe` (`account_id` ASC);


-- -----------------------------------------------------
-- Table `ewaiter`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ewaiter`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` BINARY(32) NOT NULL,
  `isblocked` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ewaiter`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ewaiter`.`session` (
  `sessionkey` BINARY(16) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `expires` DATETIME NOT NULL,
  `ip` BINARY(16) NULL DEFAULT NULL,
  CONSTRAINT `session_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ewaiter`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `user_id` ON `ewaiter`.`session` (`user_id` ASC);

CREATE INDEX `sessionkey` ON `ewaiter`.`session` (`sessionkey` ASC, `ip` ASC);


-- -----------------------------------------------------
-- Table `ewaiter`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ewaiter`.`user_role` (
  `user_id` INT(11) NOT NULL,
  `role` ENUM('system', 'account', 'caffe') NOT NULL,
  `account_id` INT(11) NOT NULL,
  `caffe_id` INT(11) NOT NULL,
  CONSTRAINT `user_role_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ewaiter`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `user_id` ON `ewaiter`.`user_role` (`user_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
